name: NetSlutter
2
​
3
on: workflow_dispatch
4
​
5
jobs:
6
  build:
7
​
8
    runs-on: windows-latest
9
    timeout-minutes: 9999
10
​
11
    steps:
12
    - name: Download Ngrok.
13
      run: |
14
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
15
        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/start.bat -OutFile start.bat
16
        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/wallpaper.png -OutFile wallpaper.png
17
        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/wallpaper.bat -OutFile wallpaper.bat
18
        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/loop.bat -OutFile loop.bat
19
    - name: Download Launcher.
20
      run: |
21
        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/launcher/Node.js.lnk -OutFile Node.js.lnk
22
        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
23
    - name: Extracting Ngrok File.
24
      run: Expand-Archive ngrok.zip
25
    - name: Connect To Account Ngrok.
26
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
27
      env:
28
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
29
    - name: Turn on Access RDP.
30
      run: | 
31
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
32
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
33
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
34
        copy wallpaper.png D:\a\wallpaper.png
35
        copy wallpaper.bat D:\a\wallpaper.bat
36
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
37
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
38
    - name: Make Tunnel.
39
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
40
    - name: Connect To Your RDP CPU 2 Core - 7GB Ram - 256 SSD.
41
      run: cmd /c start.bat
42
    - name: Successfully Created! You Can Close Tabs Now.
43
      run: cmd /c loop.bat
44
​name: NetSlutter



on: workflow_dispatch



jobs:

  build:



    runs-on: windows-latest

    timeout-minutes: 9999



    steps:

    - name: Download Ngrok.

      run: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/wallpaper.png -OutFile wallpaper.png

        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/wallpaper.bat -OutFile wallpaper.bat

        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/loop.bat -OutFile loop.bat

    - name: Download Launcher.

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/launcher/Node.js.lnk -OutFile Node.js.lnk

        Invoke-WebRequest https://raw.githubusercontent.com/testhere1122/netslutter-RDP-1/master/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"

    - name: Extracting Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect To Account Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Turn on Access RDP.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy wallpaper.png D:\a\wallpaper.png

        copy wallpaper.bat D:\a\wallpaper.bat

        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk

        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"

    - name: Make Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Connect To Your RDP CPU 2 Core - 7GB Ram - 256 SSD.

      run: cmd /c start.bat

    - name: Successfully Created! You Can Close Tabs Now.

      run: cmd /c loop.bat


